import Patient from '../models/Patient.js';
import { logActivity } from '../utils/logActivity.js';
import { Parser } from 'json2csv';

// @desc    Create new patient
// @route   POST /api/patients
// @access  Private (Any logged-in staff)
export const createPatient = async (req, res) => {
  try {
    const { name, age, gender, phone, email, address } = req.body;
    
    // patientId is auto-generated by the pre-save hook in the Patient model
    const patient = await Patient.create({
      name, 
      age, 
      gender, 
      phone, 
      email, 
      address
    });
    
    await logActivity(
      req,
      'CREATE_PATIENT',
      `Created patient ${patient.name} (${patient.patientId || 'New'})`,
      'Patient',
      patient._id
    );

    return res.status(201).json({
      success: true,
      message: "Patient created successfully",
      data: patient
    });
  } catch (error) {
    console.error("Create Patient Error:", error);
    return res.status(500).json({ 
      success: false, 
      message: error.message || "Server error while creating patient" 
    });
  }
};

// @desc    Get all patients
// @route   GET /api/patients
// @access  Private
export const getAllPatients = async (req, res) => {
  try {
    const { search, page = 1, limit = 20 } = req.query;
    const query = {};
    
    // Optional search by name or phone using regex
    if (search) {
      query.$or = [
        { name: { $regex: search, $options: 'i' } },
        { phone: { $regex: search, $options: 'i' } }
      ];
    }
    
    // Pagination logic
    const skip = (Number(page) - 1) * Number(limit);
    
    // Fetch patients sorted by newest first
    const patients = await Patient.find(query)
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(Number(limit));
      
    const totalCount = await Patient.countDocuments(query);
    
    return res.status(200).json({
      success: true,
      message: "Patients retrieved successfully",
      data: { 
        patients, 
        totalCount, 
        page: Number(page), 
        totalPages: Math.ceil(totalCount / Number(limit)) 
      }
    });
  } catch (error) {
    console.error("Get All Patients Error:", error);
    return res.status(500).json({ 
      success: false, 
      message: "Server error while retrieving patients" 
    });
  }
};

// @desc    Get patient by ID
// @route   GET /api/patients/:id
// @access  Private
export const getPatientById = async (req, res) => {
  try {
    const patient = await Patient.findById(req.params.id);
    
    if (!patient) {
      return res.status(404).json({ 
        success: false, 
        message: "Patient not found" 
      });
    }
    
    return res.status(200).json({ 
      success: true, 
      message: "Patient retrieved successfully", 
      data: patient 
    });
  } catch (error) {
    console.error("Get Patient By ID Error:", error);
    return res.status(500).json({ 
      success: false, 
      message: "Server error while retrieving patient" 
    });
  }
};

// @desc    Update patient
// @route   PUT /api/patients/:id
// @access  Private
export const updatePatient = async (req, res) => {
  try {
    const patient = await Patient.findByIdAndUpdate(
      req.params.id, 
      req.body, 
      { new: true, runValidators: true }
    );
    
    if (!patient) {
      return res.status(404).json({ 
        success: false, 
        message: "Patient not found" 
      });
    }
    
    await logActivity(
      req,
      'UPDATE_PATIENT',
      `Updated patient ${patient.name} (${patient.patientId || 'Unknown'})`,
      'Patient',
      patient._id
    );

    return res.status(200).json({ 
      success: true, 
      message: "Patient updated successfully", 
      data: patient 
    });
  } catch (error) {
    console.error("Update Patient Error:", error);
    return res.status(500).json({ 
      success: false, 
      message: error.message || "Server error while updating patient" 
    });
  }
};

// @desc    Delete patient
// @route   DELETE /api/patients/:id
// @access  Private/Admin
export const deletePatient = async (req, res) => {
  try {
    const patient = await Patient.findByIdAndDelete(req.params.id);
    
    if (!patient) {
      return res.status(404).json({ 
        success: false, 
        message: "Patient not found" 
      });
    }
    
    await logActivity(
      req,
      'DELETE_PATIENT',
      `Deleted patient ${patient.name} (${patient.patientId || 'Unknown'})`,
      'Patient',
      patient._id
    );

    return res.status(200).json({ 
      success: true, 
      message: "Patient deleted successfully" 
    });
  } catch (error) {
    console.error("Delete Patient Error:", error);
    return res.status(500).json({ 
      success: false, 
      message: "Server error while deleting patient" 
    });
  }
};

// @desc    Export all patients to CSV
// @route   GET /api/patients/export/csv
// @access  Private/Admin
export const exportPatientsCSV = async (req, res) => {
  try {
    const { search } = req.query;
    const query = {};
    
    if (search) {
      query.$or = [
        { name: { $regex: search, $options: 'i' } },
        { phone: { $regex: search, $options: 'i' } }
      ];
    }
    
    const patients = await Patient.find(query).sort({ createdAt: -1 });

    const csvData = patients.map(p => ({
      'Patient ID': p.patientId,
      'Name': p.name,
      'Age': p.age,
      'Gender': p.gender,
      'Phone': p.phone ? `="${p.phone}"` : '',
      'Email': p.email || '',
      'Address': p.address || '',
      'Registered On': new Date(p.createdAt).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
    }));

    if (csvData.length === 0) {
      return res.status(404).json({ success: false, message: 'No patients found to export' });
    }

    const fields = ['Patient ID', 'Name', 'Age', 'Gender', 'Phone', 'Email', 'Address', 'Registered On'];
    const json2csvParser = new Parser({ fields });
    const csv = json2csvParser.parse(csvData);

    const dateStr = new Date().toISOString().split('T')[0];
    res.setHeader('Content-Type', 'text/csv');
    res.setHeader('Content-Disposition', `attachment; filename=patients-export-${dateStr}.csv`);
    res.status(200).send(csv);

    await logActivity(
      req,
      'EXPORT_PATIENTS',
      `Exported ${patients.length} patients to CSV`,
      'Patient',
      null
    );
  } catch (error) {
    console.error("Export Patients Error:", error);
    return res.status(500).json({ 
      success: false, 
      message: "Server error while exporting patients" 
    });
  }
};
